# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='uploads/atividades/')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('tipo', models.CharField(choices=[('P', 'Palestra'), ('C', 'Curso')], max_length=1)),
                ('certificado', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('cargahoraria', models.PositiveSmallIntegerField()),
                ('porcent_minimo', models.PositiveSmallIntegerField()),
                ('num_vagas', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200)),
                ('dt_inicio', models.DateTimeField(verbose_name='Data de início da atividade: ')),
                ('dt_fim', models.DateTimeField(verbose_name='Data de final da atividade: ')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('dt_inicio', models.DateTimeField(verbose_name='Data de início do evento: ')),
                ('dt_fim', models.DateTimeField(verbose_name='Data final do evento')),
                ('dt_ini_inscricao', models.DateTimeField(verbose_name='Início das inscrições')),
                ('dt_fim_inscricao', models.DateTimeField(verbose_name='Fim das inscrições')),
                ('logomarca', models.ImageField(null=True, upload_to='logoeventos/%Y/%m/%d')),
                ('tipo', models.CharField(choices=[('P', 'Pago'), ('G', 'Gratuito')], max_length=1)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('P', 'Participante'), ('O', 'Organizador'), ('D', 'Doscente')], max_length=1)),
                ('status', models.CharField(choices=[('S', 'Solicitado'), ('C', 'Confirmado')], max_length=1)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao_atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Atividade')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.CharField(choices=[('P', 'Presente'), ('F', 'Faltou')], max_length=1)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Aula')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('estado', models.CharField(choices=[('ac', 'Acre'), ('al', 'Alagoas'), ('am', 'Amazonas'), ('ap', 'Amapá'), ('ba', 'Bahia'), ('ce', 'Ceará'), ('df', 'Distrito Federal'), ('es', 'Espírito Santo'), ('go', 'Goiás'), ('ma', 'Maranhão'), ('mt', 'Mato Grosso'), ('ms', 'Mato Grosso do Sul'), ('mg', 'Minas Gerais'), ('pa', 'Pará'), ('pb', 'Paraíba'), ('pr', 'Paraná'), ('pe', 'Pernambuco'), ('pi', 'Piauí'), ('rj', 'Rio de Janeiro'), ('rn', 'Rio Grande do Norte'), ('ro', 'Rondônia'), ('rs', 'Rio Grande do Sul'), ('rr', 'Roraima'), ('sc', 'Santa Catarina'), ('se', 'Sergipe'), ('sp', 'São Paulo'), ('to', 'Tocantins')], max_length=2)),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='Imagem perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='doscente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Inscricao'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Atividade'),
        ),
    ]
