# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='dt_fim',
        ),
        migrations.AddField(
            model_name='aula',
            name='hr_fim',
            field=models.TimeField(default=datetime.datetime(2016, 8, 19, 12, 45, 52, 388202, tzinfo=utc), verbose_name='Hora fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='hr_inicio',
            field=models.TimeField(default=datetime.datetime(2016, 8, 19, 12, 45, 59, 780474, tzinfo=utc), verbose_name='Hora de início'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='dt_inicio',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dt_inicio',
            field=models.DateTimeField(verbose_name='Data de início do evento'),
        ),
    ]
